Web/digital/app/urls.py
from django.conf.urls import url
from app import views

# SET THE NAMESPACE!
app_name = 'app'


urlpatterns=[
    url(r'^$',views.map,name='map'),
    url(r'^map/$',views.map,name='map'),
    url(r'^calamity/$',views.calamity,name='calamity'),
    url(r'^provisions/$',views.provisions,name='provisions'),
    url(r'^need/$',views.need,name="need"),
    url(r'^issue/$',views.issue,name='issue'),
]

Web/digital/digital/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from app import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),  
    url(r'^app/',include('app.urls')), 
]

Web/digital/app/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

Web/digital/app/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render,redirect
from django.http import HttpResponse, HttpResponseRedirect
from . import queries
import requests
import googlemaps
from .config import * 


# Create your views here.
def index(request):
    return render(request,'app/map.html')

def appindex(request):
    return render(request,'app/map.html')

def map(request):
    # FSWMCH
    if(request.method == 'POST'):
        # food = request.POST.get('cbx1')
        # shelter = request.POST.get('cbx2')
        # water = request.POST.get('cbx3')
        # medicine = request.POST.get('cbx4')
        # cloth = request.POST.get('cbx5')
        # hygenie = request.POST.get('cbx6')
        fin = []
        for i in range(1,7):
            temp = request.POST.get('cbx'+str(i))
            if temp == 'on':
                fin.append('1')
            else:
                fin.append('0')
        print(fin)
        count=1
        result = queries.find_specific_donors(fin)
        print(result)
        # result = [1,2,3,4]
        return render(request,'app/map.html',{"result": result, "fin":fin})
    else:
        donors = queries.find_donors()
        # print(donors['id'])
        list = []
        for i in donors:
            list.append(donors[i])
        return render(request,'app/map.html',{'list':list})

def retreive_area(lat,lon):
    print("Retreiving data")
    gmaps = googlemaps.Client(key="AIzaSyAwAdfRMQoKv8Tmc4iD2KsDCXQfWoxVJkk")
    reverse_geocode_result = gmaps.reverse_geocode((lat, lon))
    print(reverse_geocode_result)
    return 1
    #key = key.upper()
    # print(loc,key)
    # query_result = google_places.nearby_search(location=loc, keyword=key, radius=2000, types=[type_map[key]])
    # places_data = []        # name,number,addr
    # for place in query_result.places:
    #     # print(place.place_id)
    #     x = place.get_details()
    #     places_data.append([place.name,place.local_phone_number,place.vicinity])
    # if len(places_data):
    #     return places_data[0]

def calamity(request):
    sos = queries.get_sos()
    # r = requests.get("https://api.ipdata.co?api-key="+GLapikey).json()
    #lon,lat = r["longitude"],r["latitude"]
    #details = retreive_area(lat,lon)
    #print(details)
    return render(request,'app/calamity.html',{'list':sos})

def provisions(request):
    temp = queries.get_issue()
    print("//////////////")
    print(temp)
    return render(request,'app/provisions.html',{'src': temp})

def need(request):
    if(request.method == 'POST'):
        fin = []
        for i in range(1,7):
            temp = request.POST.get('cb'+str(i))
            if temp == 'on':
                fin.append('1')
            else:
                fin.append('0')
        print(fin)
        index = queries.number_of_req("donor")
        rd = 0
        fswmch = "".join(fin)
        desc = request.POST.get('descr')
        address = request.POST.get('addr')
        name = request.POST.get('name')
        number = request.POST.get('phn')
        
        queries.add_donors(index,rd,fswmch,desc,address,name,number)
        return render(request,'app/map.html')

def issue(request):
    if(request.method == "POST"):
        index = queries.number_of_req("issues")
        name = request.POST.get("name")
        descr = request.POST.get("descr")
        date = request.POST.get("date")
        dept = request.POST.get("dept")
        print(name,descr,date,dept)
        queries.add_issue(descr,name,dept,date)
    return render(request, 'app/map.html')

# def adddonors(request):
#     if(request.method == 'POST'):
#         name = request.POST.get('name')
#         dob = request.POST.get('dob')
#         state = request.POST.get('state')
#         district = request.POST.get('district')
#         block = request.POST.get('block')
#         pincode = request.POST.get('pincode')
#         phone = request.POST.get('phone')
#         temp = request.POST.getlist('checks[]')
#         #data = Crop.objects.filter(region=pincode)[0]
#         #x = Farmer(name=name,dob=dob,state=state,district=district,block=block,pincode=pincode,phone=phone,crops=crops,data=data)
#         #x.save()
#         #u = reverse('app:dashboard',kwargs={'username':str(request.user)})
#         #print(str(request.user))
#         #return HttpResponseRedirect(u)
#     else:
#         #return render(request,'app/farmer.html',{})

Web/digital/templates/app/appindex.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Home</title>
</head>
<body>
    <h1>Hello App</h1>
</body>
</html>

Web/digital/templates/app/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Digital</title>
        <script src="{% static 'js/bundle.js' %}"></script>
        <link rel="stylesheet" href="{% static 'css/map.css' %}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <script
        src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
        crossorigin="anonymous"></script>
    </head>
    <body>
        <input type="checkbox" id="nav">
        <div class="content">
            <div class="nav">
                <div class="nav__list">
                    <a href="{% url 'app:calamity' %}"><div class="nav__list--item">Home</div></a>
                    <a href="{% url 'app:provisions' %}"><div class="nav__list--item">Issues</div></a>
                    <a href="{% url 'app:map' %}"><div class="nav__list--item">Map</div></a>
                </div>
            </div>
            <div class="page-wrap">
                <label for="nav">☰</label>
            {% block body_block %}
            {% endblock %}
            </div>
        </div>
        <!-- <script src="{% static 'js/forms.js' %}"></script> -->
        <script src="{% static 'js/result.js' %}"></script>
    </body>
</html>

Web/digital/templates/app/calamity.html
{% extends 'app/base.html' %}

{% block body_block %}
<div class="pc-tab">
        <input id="tab1" type="radio" name="pct" />
        <input id="tab2" type="radio" name="pct" checked/>
        <input id="tab3" type="radio" name="pct" />
        <nav>
            <ul>
                <li class="tab1">
                    <label for="tab1" style="display: none;">High</label>
                </li>
                <li class="tab2">
                    <label for="tab2">Current</label>
                </li>
                <li class="tab3">
                    <label for="tab3">Contact</label>
                </li>
            </ul>
        </nav>
        <section>
            <div class="tab1 tab">
                High
            </div>
            <div class="tab2 tab">
                <div class="cardcontainer">
                    {% for x in list %}
                    <div class="card">
                        <div class="card__head">{{ x.0 }}</div><br>
                        <div class="card__sub"> {{ x.2 }}</div><br>
                        <div class="card__sub">{{ x.3 }}</div>
                        <div class="card__sub">{{ x.1 }}</div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            <div class="tab3 tab">
                <div class="cardcontainer">
                    <div class="card" xstyle="background: #dd9554;">
                        <div class="card__head">Police</div>
                        <i class="fa fa-user-secret" style="font-size: 3.5rem"></i>
                        <div class="card__sub">Contact: <a href="callto:02226479372">022 2647 9372</a></div>
                    </div>
                    <div class="card" xstyle="background: #e24a44">
                        <div class="card__head">Fire</div>
                        <i class="fa fa-fire-extinguisher" style="font-size: 3.5rem"></i>
                        <div class="card__sub">Contact: <a href="callto:02226435206">022 2643 5206</a></div>
                    </div>
                    <div class="card" xstyle="background: #7777ff">
                        <div class="card__head">Ambulance</div>
                        <i class="fa fa-ambulance" style="font-size: 3.5rem"></i>
                        <div class="card__sub">Contact: <a href="callto:02224376568">022 2437 6568</a></div>
                    </div>
                </div>
            </div>
        </section>
    </div>
{% endblock %}

Web/digital/templates/app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Home</title>
</head>
<body>
    <h1>Hello World</h1>
</body>
</html>

Web/digital/templates/app/map.html
{% extends 'app/base.html' %}

{% block body_block %}
<script src="../../static/js/map.js"></script>
<script>
    var xmarkers = []
    {% for item in result %}
    var temp = []    
    var cords = {{item.2}}
    var name = '{{item.3}}'
    var descr = '{{item.4}}'
    var num = '{{item.5}}'
    var addr = '{{item.6}}'
    temp.push(cords)
    temp.push(name)
    temp.push(descr)
    temp.push(num)
    temp.push(addr)
    xmarkers.push(temp)
    // console.log(cords)
    {% endfor %}
</script>
<div class="pc-tab">
    <input id="tab1" type="radio" name="pct" />
    <input id="tab2" type="radio" name="pct" />
    <input id="tab3" type="radio" name="pct" checked />
    <nav>
        <ul>
            <li class="tab1">
                <label for="tab1" style="display: none;">First Tab</label>
            </li>
            <li class="tab2">
                <label for="tab2">Need</label>
            </li>
            <li class="tab3">
                <label for="tab3">Donate</label>
            </li>
        </ul>
    </nav>
    <section>
        <div class="tab1 tab">
        </div>
        <div class="tab2 tab">
            <form action="{% url 'app:need' %}" method="post">
                {% csrf_token %}
                <div class="fildscontainer">
                    <div class="filds">
                        <input type="text" id="name" placeholder="Name" name="name">
                        <label for="name">Name</label>
                    </div>
                    <div class="filds">
                        <input type="text" id="descr" placeholder="short description" name="descr">
                        <label for="description">Description</label>
                    </div>
                    <div class="filds">
                        <input type="text" id="addr" placeholder="Address" name="addr">
                        <label for="address">Address</label>
                    </div>
                    <div class="filds">
                        <input type="text" id="phn" placeholder="Phone" name="phn">
                        <label for="phone">Phone</label>
                    </div>
                </div>
                <div class="tgl-container">
                    <ul class="tg-list">
                        <li class="tg-list-item">
                            <input class="tgl tgl-ios" id="cb1" type="checkbox" name="cb1" />
                            <label class="tgl-btn" for="cb1"></label>
                            <div class="tgl-list-item-name"><i class="fa fa-cutlery"></i> Food</div>
                        </li>
                        <li class="tg-list-item">
                            <input class="tgl tgl-ios" id="cb2" type="checkbox" name="cb2" />
                            <label class="tgl-btn" for="cb2"></label>
                            <div class="tgl-list-item-name"><i class="fa fa-bed"></i> Shelter</div>
                        </li>
                        <li class="tg-list-item">
                            <input class="tgl tgl-ios" id="cb3" type="checkbox" name="cb3" />
                            <label class="tgl-btn" for="cb3"></label>
                            <div class="tgl-list-item-name"><i class="fa fa-black-tie"></i> Clothing</div>
                        </li>
                    </ul>
                    <ul class="tg-list">
                        <li class="tg-list-item">
                            <input class="tgl tgl-ios" id="cb4" type="checkbox" name="cb4" />
                            <label class="tgl-btn" for="cb4"></label>
                            <div class="tgl-list-item-name"><i class="fa fa-tint"></i> Water</div>
                        </li>
                        <li class="tg-list-item">
                            <input class="tgl tgl-ios" id="cb5" type="checkbox" name="cb5" />
                            <label class="tgl-btn" for="cb5"></label>
                            <div class="tgl-list-item-name"><i class="fa fa-medkit"></i> Medkit</div>
                        </li>
                        <li class="tg-list-item">
                            <input class="tgl tgl-ios" id="cb6" type="checkbox" name="cb6" />
                            <label class="tgl-btn" for="cb6"></label>
                            <div class="tgl-list-item-name"><i class="fa fa-cubes"></i> Other</div>
                        </li>
                    </ul>
                </div>
                <button type="submit" id="needForm"><strong>Need</strong></button>
            </form>
        </div>
        <div class="tab3 tab">
            <div id="map"></div>
            <!-- <button onclick="geoloc()">Submit</button> -->
            <form action="{% url 'app:map' %}" method="post">
                {% csrf_token %}
                <div class="tgl-container">
                    <ul class="tg-list">
                        <li class="tg-list-item">
                            <input class="tgl tgl-ios" id="cbx1" type="checkbox" name="cbx1" />
                            <label class="tgl-btn" for="cbx1"></label>
                            <div class="tgl-list-item-name"><i class="fa fa-cutlery"></i> Food</div>
                        </li>
                        <li class="tg-list-item">
                            <input class="tgl tgl-ios" id="cbx2" type="checkbox" name="cbx2" />
                            <label class="tgl-btn" for="cbx2"></label>
                            <div class="tgl-list-item-name"><i class="fa fa-bed"></i> Shelter</div>
                        </li>
                        <li class="tg-list-item">
                            <input class="tgl tgl-ios" id="cbx3" type="checkbox" name="cbx3" />
                            <label class="tgl-btn" for="cbx3"></label>
                            <div class="tgl-list-item-name"><i class="fa fa-black-tie"></i> Clothing</div>
                        </li>
                    </ul>
                    <ul class="tg-list">
                        <li class="tg-list-item">
                            <input class="tgl tgl-ios" id="cbx4" type="checkbox" name="cbx4" />
                            <label class="tgl-btn" for="cbx4"></label>
                            <div class="tgl-list-item-name"><i class="fa fa-tint"></i> Water</div>
                        </li>
                        <li class="tg-list-item">
                            <input class="tgl tgl-ios" id="cbx5" type="checkbox" name="cbx5" />
                            <label class="tgl-btn" for="cbx5"></label>
                            <div class="tgl-list-item-name"><i class="fa fa-medkit"></i> Medkit</div>
                        </li>
                        <li class="tg-list-item">
                            <input class="tgl tgl-ios" id="cbx6" type="checkbox" name="cbx6" />
                            <label class="tgl-btn" for="cbx6"></label>
                            <div class="tgl-list-item-name"><i class="fa fa-cubes"></i> Other</div>
                        </li>
                    </ul>
                </div>
                <button type="submit" id="provForm"><strong>Provide</strong></button>
            </form>
        </div>
    </section>
</div>
<script>
    var button = [] 
    {% for i in fin %}
        button.push('{{i}}') 
    {% endfor %}
    console.log("TTTTTTTTTTTTT")
    console.log(button)
    for (var i = 0; i < 6; i++) {
        if (button[i] == "1") {
            var radio = document.getElementById("cbx" + String(i + 1))
            console.log(radio)
            radio.checked = true;
        }
    }
</script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAwAdfRMQoKv8Tmc4iD2KsDCXQfWoxVJkk&callback=initMap">
</script>
{% endblock %}

Web/digital/templates/app/provisions.html
{% extends 'app/base.html' %}

{% block body_block %}
<div class="pc-tab">
    <input id="tab1" type="radio" name="pct" />
    <input id="tab2" type="radio" name="pct" />
    <input id="tab3" type="radio" name="pct" checked/>
    <nav>
        <ul>
            <li class="tab1">
                <label for="tab1" style="display: none;">High</label>
            </li>
            <li class="tab2">
                <label for="tab2">New</label>
            </li>
            <li class="tab3">
                <label for="tab3">History</label>
            </li>
        </ul>
    </nav>
    <section>
        <div class="tab1 tab">
            High
        </div>
        <div class="tab2 tab">
            <form action="{% url 'app:issue' %}" method="post">
                {% csrf_token %}
                <div class="fildscontainer">
                    <div class="filds">
                        <input type="text" id="name" placeholder="name" name="name">
                        <label for="name">Name</label>
                    </div>
                    <div class="filds">
                        <input type="text" id="description" placeholder="short description" name="descr">
                        <label for="description">Description</label>
                    </div>
                    <div class="filds">
                        <input type="date" id="date" name="date">
                        <label for="date">Issue Discovered</label>
                    </div>
                    <div class="filds">
                        <input type="text" id="dept" placeholder="muncipal" name="dept">
                        <label for="dept">Department</label>
                    </div>
                </div>
                <button type="submit" id="issueForm"><strong>Register</strong></button>
            </form>
        </div>
        <div class="tab3 tab">
            <div class="result">
                {% for i in src %}
                <div class="resultcard">
                    <img class="resultcard__img" src="https://picsum.photos/200/200/?random" alt="#">
                    <h2 class="resultcard__heading">{{i.0}}</h2>
                    <h4 class="resultcard__source">{{i.2}}</h4>
                </div>
                <div class="summarycard">
                    <div class="summarycard__left">
                        <img src="https://picsum.photos/200/200/?random" alt="#">
                    </div>
                    <div class="summarycard__right">
                        <div class="feature">
                            <ul class="feature__list feature__list--right">
                                <li class="feature__item"><a href=""><i class="fa fa-thumbs-up"></i></a></li>
                                <li class="feature__item"><a href=""><i class="fa fa-thumbs-down"></i></a></li>
                            </ul>
                        </div>
                        <h2 class="summarycard__heading">{{i.0}}</h2>
                        <h4 class="summarycard__source">{{i.2}}</h4>
                        <h6 class="summarycard__source">{{i.1}}</h6>
                        <div class="progressbar">
                            <div class="progressbar__head">Progress-Bar</div>
                            <div class="progressbar__main">
                                <div class="progressbar__fill" fillVal={{i.4}}></div>
                            </div>
                            
                        </div>
                        <div class="feature">
                            <ul class="feature__list feature__list--right">
                                <li class="feature__item"><a target="_target" href="{{i.1}}" title="Read More" class="fa fa-newspaper-o"></i></a></li>
                                <li class="feature__item"><a href="" title="Facebook Share"><i class="fa fa-facebook"></i></a></li>
                                <li class="feature__item"><a href="" title="Twitter Share"><i class="fa fa-twitter"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                {% endfor %}
                <script>
                    var fill = document.getElementsByClassName("progressbar__fill");
                    for(var i=0; i < fill.length; i++){
                        if(fill[i].getAttribute("fillVal") < 2){
                            fill[i].style.background = "red"
                        }else if(fill[i].getAttribute("fillVal") < 3){
                            fill[i].style.background = "blue"
                        }else{
                            fill[i].style.background = "green"
                        }
                        fill[i].style.width = String(100*fill[i].getAttribute("fillVal")/3) + "%"
                        console.log(String(100*fill[i].getAttribute("fillVal")/3) + "%");
                    }
                </script>
            </div>
            
        </div>
    </section>
</div>
{% endblock %}

<!-- 
    
-->

<!-- 
    
    
-->